//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicAuth.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicnicAuth.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountEndpointName {
            get {
                return ResourceManager.GetString("AccountEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przystawka|appetizer.
        /// </summary>
        internal static string AppetizerTags {
            get {
                return ResourceManager.GetString("AppetizerTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicnicAuth.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Account/Token.
        /// </summary>
        internal static string AuthTokenRoute {
            get {
                return ResourceManager.GetString("AuthTokenRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string CorsAllowAllWildcard {
            get {
                return ResourceManager.GetString("CorsAllowAllWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found in out database..
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłany plik nie był formatu graficznego..
        /// </summary>
        internal static string FileNotImageMessage {
            get {
                return ResourceManager.GetString("FileNotImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/form-data.
        /// </summary>
        internal static string FormDataMimeType {
            get {
                return ResourceManager.GetString("FormDataMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formData.
        /// </summary>
        internal static string FormDataParameterTypeName {
            get {
                return ResourceManager.GetString("FormDataParameterTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekord o podanym id nie istnieje..
        /// </summary>
        internal static string GenericNotFoundMessage {
            get {
                return ResourceManager.GetString("GenericNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grant_type.
        /// </summary>
        internal static string GrantTypeName {
            get {
                return ResourceManager.GetString("GrantTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferably grant_type=password.
        /// </summary>
        internal static string GrantTypeParameterDescription {
            get {
                return ResourceManager.GetString("GrantTypeParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string ImageDataTypeName {
            get {
                return ResourceManager.GetString("ImageDataTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć zdjęcia którego sam nie dodałeś..
        /// </summary>
        internal static string ImageNotAuthorized {
            get {
                return ResourceManager.GetString("ImageNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image file.
        /// </summary>
        internal static string ImageParameterDescription {
            get {
                return ResourceManager.GetString("ImageParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image file.
        /// </summary>
        internal static string ImageParameterName {
            get {
                return ResourceManager.GetString("ImageParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formData.
        /// </summary>
        internal static string ImageParameterType {
            get {
                return ResourceManager.GetString("ImageParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image_Post.
        /// </summary>
        internal static string ImagePostOperationId {
            get {
                return ResourceManager.GetString("ImagePostOperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik nie znajduje się w naszej bazie..
        /// </summary>
        internal static string IngredientNotFoundMessage {
            get {
                return ResourceManager.GetString("IngredientNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć nie swojego składnika..
        /// </summary>
        internal static string IngredientQuantityDeleteForbiddenMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityDeleteForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz edytować nie swojej lodówki..
        /// </summary>
        internal static string IngredientQuantityPutForbiddenMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityPutForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided request was invalid.
        /// </summary>
        internal static string InvalidRequestString {
            get {
                return ResourceManager.GetString("InvalidRequestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request nie jest typu multipart..
        /// </summary>
        internal static string IsNotMultipartMessage {
            get {
                return ResourceManager.GetString("IsNotMultipartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string JpegMediaHeader {
            get {
                return ResourceManager.GetString("JpegMediaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string JsonMediaHeader {
            get {
                return ResourceManager.GetString("JsonMediaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny login lub hasło..
        /// </summary>
        internal static string LoginValidationMessage {
            get {
                return ResourceManager.GetString("LoginValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string PasswordParameterName {
            get {
                return ResourceManager.GetString("PasswordParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do wykonania tej akcji musisz być zalogowany..
        /// </summary>
        internal static string PicnicAuthUnauthorizedMessage {
            get {
                return ResourceManager.GetString("PicnicAuthUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/png.
        /// </summary>
        internal static string PngMediaHeader {
            get {
                return ResourceManager.GetString("PngMediaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz podejrzeć czyjejś notatki..
        /// </summary>
        internal static string RecipeNoteNotOwnedGetMessage {
            get {
                return ResourceManager.GetString("RecipeNoteNotOwnedGetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get authorization token (bearer).
        /// </summary>
        internal static string TokenEndpointDescription {
            get {
                return ResourceManager.GetString("TokenEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token granted.
        /// </summary>
        internal static string TokenGetString {
            get {
                return ResourceManager.GetString("TokenGetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit was not found in our database..
        /// </summary>
        internal static string UnitNotFoundMessage {
            get {
                return ResourceManager.GetString("UnitNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string UrlEncodedContentType {
            get {
                return ResourceManager.GetString("UrlEncodedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string UsernameParameterName {
            get {
                return ResourceManager.GetString("UsernameParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\bin\PicnicAuth.Api.XML.
        /// </summary>
        internal static string XmlCommentsPath {
            get {
                return ResourceManager.GetString("XmlCommentsPath", resourceCulture);
            }
        }
    }
}
