//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicAuth.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicnicAuth.Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9CCFA6BD1C364830910E4B024858DDC0.
        /// </summary>
        public static string AppetizerImageId {
            get {
                return ResourceManager.GetString("AppetizerImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przystawka|appetizer.
        /// </summary>
        public static string AppetizerTags {
            get {
                return ResourceManager.GetString("AppetizerTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Potwierdź hasło&apos; nie może być puste..
        /// </summary>
        public static string ConfirmPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości w polach nowe hasło oraz potwierdzenie nowego hasła są różne..
        /// </summary>
        public static string ConfirmPasswordValidationMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może być pusty..
        /// </summary>
        public static string CreateRecipeDescriptionEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może przekraczać {0} znaków..
        /// </summary>
        public static string CreateRecipeDescriptionLengthValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W przepisie musi znajdować się przynajmniej jeden składnik..
        /// </summary>
        public static string CreateRecipeIngredientsEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jeden ze składników nie znajduje się w bazie danych..
        /// </summary>
        public static string CreateRecipeIngredientsExistsValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może być pusta..
        /// </summary>
        public static string CreateRecipeTitleEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeTitleEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może przekraczać 100 znaków..
        /// </summary>
        public static string CreateRecipeTitleLengthValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeTitleLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Hasło&apos; nie może być puste..
        /// </summary>
        public static string CurrentPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podane hasło nie jest poprawne..
        /// </summary>
        public static string CurrentPasswordValidationError {
            get {
                return ResourceManager.GetString("CurrentPasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43410B819BFB4FDC8F5BF892976FEE47.
        /// </summary>
        public static string DessertImageId {
            get {
                return ResourceManager.GetString("DessertImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deser|desssert|sweet.
        /// </summary>
        public static string DessertTags {
            get {
                return ResourceManager.GetString("DessertTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F62716B6F62716B6F62716B6F62716B6.
        /// </summary>
        public static string DiGgeRetsae {
            get {
                return ResourceManager.GetString("DiGgeRetsae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość opisu nie może przekraczać 100 znaków..
        /// </summary>
        public static string EditIngredientQuantityDescriptionValidationMessage {
            get {
                return ResourceManager.GetString("EditIngredientQuantityDescriptionValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Adres e-mail&apos; nie może być puste..
        /// </summary>
        public static string EmailEmptyValidationMessage {
            get {
                return ResourceManager.GetString("EmailEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email jest już zajęty..
        /// </summary>
        public static string EmailExistsValidationMessage {
            get {
                return ResourceManager.GetString("EmailExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email nie przechodzi walidacji wyrażeniem regularnym..
        /// </summary>
        public static string EmailRegexValidationMessage {
            get {
                return ResourceManager.GetString("EmailRegexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może być pusty..
        /// </summary>
        public static string EmptyCommentValidationMessage {
            get {
                return ResourceManager.GetString("EmptyCommentValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} nie może być puste..
        /// </summary>
        public static string EmptyGenericValidationMessage {
            get {
                return ResourceManager.GetString("EmptyGenericValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć czyjegoś rekordu..
        /// </summary>
        public static string GenericNotOwnerDeleteMessage {
            get {
                return ResourceManager.GetString("GenericNotOwnerDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz edytować czyjegoś rekordu..
        /// </summary>
        public static string GenericNowOwnerPutMessage {
            get {
                return ResourceManager.GetString("GenericNowOwnerPutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika nie może być pusta..
        /// </summary>
        public static string IngredientNameEmptyValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika musi mieścić się w granicach 1-100 znaków..
        /// </summary>
        public static string IngredientNameLengthValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mamy już składnik o takiej nazwie i w tej jednostce..
        /// </summary>
        public static string IngredientNameUniqueValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameUniqueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik o podanym Id nie istnieje..
        /// </summary>
        public static string IngredientQuantityIngredientValidationMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityIngredientValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość musi być liczbą dodatnią..
        /// </summary>
        public static string IngredientQuantityQuantityValidationMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityQuantityValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o podanym Id nie istnieje..
        /// </summary>
        public static string IngredientUnitExistMessage {
            get {
                return ResourceManager.GetString("IngredientUnitExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może przekraczać {0} znaków..
        /// </summary>
        public static string InputCommentValidationMessage {
            get {
                return ResourceManager.GetString("InputCommentValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Login&apos; nie może być puste..
        /// </summary>
        public static string LoginEmptyValidationMessage {
            get {
                return ResourceManager.GetString("LoginEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A9DF6800D94C4149B4AD47E46CC9BD1E.
        /// </summary>
        public static string MainCourseImageId {
            get {
                return ResourceManager.GetString("MainCourseImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Nowe hasło&apos; nie może być puste..
        /// </summary>
        public static string NewPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("NewPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi składać się z minimum {0} znaków..
        /// </summary>
        public static string PasswordLengthValidationMessage {
            get {
                return ResourceManager.GetString("PasswordLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena nie może być pusta..
        /// </summary>
        public static string RateEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RateEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena musi mieścić się w skali 0-10 (liczba całkowita).
        /// </summary>
        public static string RateValidationMessage {
            get {
                return ResourceManager.GetString("RateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole notatka nie może być puste..
        /// </summary>
        public static string RecipeNoteEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka nie może być dłuższ niż 200 znaków..
        /// </summary>
        public static string RecipeNoteLengthValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepis o podanym RecipeId nie istnieje..
        /// </summary>
        public static string RecipeNoteRecipeExistsValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole RecipeId nie może być puste..
        /// </summary>
        public static string RecipeNoteRecipeIdEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeIdEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthUser has not been found in logged company&apos;s collection..
        /// </summary>
        public static string SwaggerAuthUserNotFoundMessage {
            get {
                return ResourceManager.GetString("SwaggerAuthUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is not logged in..
        /// </summary>
        public static string SwaggerCompanyNotLoggedInMessage {
            get {
                return ResourceManager.GetString("SwaggerCompanyNotLoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string TagsDelimiter {
            get {
                return ResourceManager.GetString("TagsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki nie może być pusta..
        /// </summary>
        public static string UnitEmptyValidationMessage {
            get {
                return ResourceManager.GetString("UnitEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o takiej nazwie już istnieje..
        /// </summary>
        public static string UnitExistsValidationMessage {
            get {
                return ResourceManager.GetString("UnitExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki musi mieścić się w granicach 1-50 znaków..
        /// </summary>
        public static string UnitValidationMessage {
            get {
                return ResourceManager.GetString("UnitValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o podanej nazwie już istnieje..
        /// </summary>
        public static string UsernameExistsValidationMessage {
            get {
                return ResourceManager.GetString("UsernameExistsValidationMessage", resourceCulture);
            }
        }
    }
}
