//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicnicAuth.Validation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicnicAuth.Validation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9CCFA6BD1C364830910E4B024858DDC0.
        /// </summary>
        internal static string AppetizerImageId {
            get {
                return ResourceManager.GetString("AppetizerImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9CCFA6BD1C364830910E4B024858DDC0.
        /// </summary>
        internal static string AppetizerImageId1 {
            get {
                return ResourceManager.GetString("AppetizerImageId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przystawka|appetizer.
        /// </summary>
        internal static string AppetizerTags {
            get {
                return ResourceManager.GetString("AppetizerTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przystawka|appetizer.
        /// </summary>
        internal static string AppetizerTags1 {
            get {
                return ResourceManager.GetString("AppetizerTags1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Potwierdź hasło&apos; nie może być puste..
        /// </summary>
        internal static string ConfirmPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Potwierdź hasło&apos; nie może być puste..
        /// </summary>
        internal static string ConfirmPasswordEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("ConfirmPasswordEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości w polach nowe hasło oraz potwierdzenie nowego hasła są różne..
        /// </summary>
        internal static string ConfirmPasswordValidationMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości w polach nowe hasło oraz potwierdzenie nowego hasła są różne..
        /// </summary>
        internal static string ConfirmPasswordValidationMessage1 {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości w polach nowe hasło oraz potwierdzenie nowego hasła są różne..
        /// </summary>
        internal static string ConfirmPasswordValidationMessage2 {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może być pusty..
        /// </summary>
        internal static string CreateRecipeDescriptionEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może być pusty..
        /// </summary>
        internal static string CreateRecipeDescriptionEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może przekraczać {0} znaków..
        /// </summary>
        internal static string CreateRecipeDescriptionLengthValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis przepisu nie może przekraczać {0} znaków..
        /// </summary>
        internal static string CreateRecipeDescriptionLengthValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeDescriptionLengthValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W przepisie musi znajdować się przynajmniej jeden składnik..
        /// </summary>
        internal static string CreateRecipeIngredientsEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W przepisie musi znajdować się przynajmniej jeden składnik..
        /// </summary>
        internal static string CreateRecipeIngredientsEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jeden ze składników nie znajduje się w bazie danych..
        /// </summary>
        internal static string CreateRecipeIngredientsExistsValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przynajmniej jeden ze składników nie znajduje się w bazie danych..
        /// </summary>
        internal static string CreateRecipeIngredientsExistsValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeIngredientsExistsValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może być pusta..
        /// </summary>
        internal static string CreateRecipeTitleEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeTitleEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może być pusta..
        /// </summary>
        internal static string CreateRecipeTitleEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeTitleEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może przekraczać 100 znaków..
        /// </summary>
        internal static string CreateRecipeTitleLengthValidationMessage {
            get {
                return ResourceManager.GetString("CreateRecipeTitleLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przepisu nie może przekraczać 100 znaków..
        /// </summary>
        internal static string CreateRecipeTitleLengthValidationMessage1 {
            get {
                return ResourceManager.GetString("CreateRecipeTitleLengthValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Hasło&apos; nie może być puste..
        /// </summary>
        internal static string CurrentPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Hasło&apos; nie może być puste..
        /// </summary>
        internal static string CurrentPasswordEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("CurrentPasswordEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podane hasło nie jest poprawne..
        /// </summary>
        internal static string CurrentPasswordValidationError {
            get {
                return ResourceManager.GetString("CurrentPasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podane hasło nie jest poprawne..
        /// </summary>
        internal static string CurrentPasswordValidationError1 {
            get {
                return ResourceManager.GetString("CurrentPasswordValidationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43410B819BFB4FDC8F5BF892976FEE47.
        /// </summary>
        internal static string DessertImageId {
            get {
                return ResourceManager.GetString("DessertImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43410B819BFB4FDC8F5BF892976FEE47.
        /// </summary>
        internal static string DessertImageId1 {
            get {
                return ResourceManager.GetString("DessertImageId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deser|desssert|sweet.
        /// </summary>
        internal static string DessertTags {
            get {
                return ResourceManager.GetString("DessertTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deser|desssert|sweet.
        /// </summary>
        internal static string DessertTags1 {
            get {
                return ResourceManager.GetString("DessertTags1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F62716B6F62716B6F62716B6F62716B6.
        /// </summary>
        internal static string DiGgeRetsae {
            get {
                return ResourceManager.GetString("DiGgeRetsae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F62716B6F62716B6F62716B6F62716B6.
        /// </summary>
        internal static string DiGgeRetsae1 {
            get {
                return ResourceManager.GetString("DiGgeRetsae1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość opisu nie może przekraczać 100 znaków..
        /// </summary>
        internal static string EditIngredientQuantityDescriptionValidationMessage {
            get {
                return ResourceManager.GetString("EditIngredientQuantityDescriptionValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość opisu nie może przekraczać 100 znaków..
        /// </summary>
        internal static string EditIngredientQuantityDescriptionValidationMessage1 {
            get {
                return ResourceManager.GetString("EditIngredientQuantityDescriptionValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Adres e-mail&apos; nie może być puste..
        /// </summary>
        internal static string EmailEmptyValidationMessage {
            get {
                return ResourceManager.GetString("EmailEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Adres e-mail&apos; nie może być puste..
        /// </summary>
        internal static string EmailEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("EmailEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email jest już zajęty..
        /// </summary>
        internal static string EmailExistsValidationMessage {
            get {
                return ResourceManager.GetString("EmailExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email jest już zajęty..
        /// </summary>
        internal static string EmailExistsValidationMessage1 {
            get {
                return ResourceManager.GetString("EmailExistsValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email nie przechodzi walidacji wyrażeniem regularnym..
        /// </summary>
        internal static string EmailRegexValidationMessage {
            get {
                return ResourceManager.GetString("EmailRegexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email nie przechodzi walidacji wyrażeniem regularnym..
        /// </summary>
        internal static string EmailRegexValidationMessage1 {
            get {
                return ResourceManager.GetString("EmailRegexValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może być pusty..
        /// </summary>
        internal static string EmptyCommentValidationMessage {
            get {
                return ResourceManager.GetString("EmptyCommentValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może być pusty..
        /// </summary>
        internal static string EmptyCommentValidationMessage1 {
            get {
                return ResourceManager.GetString("EmptyCommentValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} nie może być puste..
        /// </summary>
        internal static string EmptyGenericValidationMessage {
            get {
                return ResourceManager.GetString("EmptyGenericValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} nie może być puste..
        /// </summary>
        internal static string EmptyGenericValidationMessage1 {
            get {
                return ResourceManager.GetString("EmptyGenericValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć czyjegoś rekordu..
        /// </summary>
        internal static string GenericNotOwnerDeleteMessage {
            get {
                return ResourceManager.GetString("GenericNotOwnerDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć czyjegoś rekordu..
        /// </summary>
        internal static string GenericNotOwnerDeleteMessage1 {
            get {
                return ResourceManager.GetString("GenericNotOwnerDeleteMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz edytować czyjegoś rekordu..
        /// </summary>
        internal static string GenericNowOwnerPutMessage {
            get {
                return ResourceManager.GetString("GenericNowOwnerPutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz edytować czyjegoś rekordu..
        /// </summary>
        internal static string GenericNowOwnerPutMessage1 {
            get {
                return ResourceManager.GetString("GenericNowOwnerPutMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika nie może być pusta..
        /// </summary>
        internal static string IngredientNameEmptyValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika nie może być pusta..
        /// </summary>
        internal static string IngredientNameEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("IngredientNameEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika musi mieścić się w granicach 1-100 znaków..
        /// </summary>
        internal static string IngredientNameLengthValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa składnika musi mieścić się w granicach 1-100 znaków..
        /// </summary>
        internal static string IngredientNameLengthValidationMessage1 {
            get {
                return ResourceManager.GetString("IngredientNameLengthValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mamy już składnik o takiej nazwie i w tej jednostce..
        /// </summary>
        internal static string IngredientNameUniqueValidationMessage {
            get {
                return ResourceManager.GetString("IngredientNameUniqueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mamy już składnik o takiej nazwie i w tej jednostce..
        /// </summary>
        internal static string IngredientNameUniqueValidationMessage1 {
            get {
                return ResourceManager.GetString("IngredientNameUniqueValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik o podanym Id nie istnieje..
        /// </summary>
        internal static string IngredientQuantityIngredientValidationMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityIngredientValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik o podanym Id nie istnieje..
        /// </summary>
        internal static string IngredientQuantityIngredientValidationMessage1 {
            get {
                return ResourceManager.GetString("IngredientQuantityIngredientValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość musi być liczbą dodatnią..
        /// </summary>
        internal static string IngredientQuantityQuantityValidationMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityQuantityValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość musi być liczbą dodatnią..
        /// </summary>
        internal static string IngredientQuantityQuantityValidationMessage1 {
            get {
                return ResourceManager.GetString("IngredientQuantityQuantityValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o podanym Id nie istnieje..
        /// </summary>
        internal static string IngredientUnitExistMessage {
            get {
                return ResourceManager.GetString("IngredientUnitExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o podanym Id nie istnieje..
        /// </summary>
        internal static string IngredientUnitExistMessage1 {
            get {
                return ResourceManager.GetString("IngredientUnitExistMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może przekraczać {0} znaków..
        /// </summary>
        internal static string InputCommentValidationMessage {
            get {
                return ResourceManager.GetString("InputCommentValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz nie może przekraczać {0} znaków..
        /// </summary>
        internal static string InputCommentValidationMessage1 {
            get {
                return ResourceManager.GetString("InputCommentValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Login&apos; nie może być puste..
        /// </summary>
        internal static string LoginEmptyValidationMessage {
            get {
                return ResourceManager.GetString("LoginEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Login&apos; nie może być puste..
        /// </summary>
        internal static string LoginEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("LoginEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A9DF6800D94C4149B4AD47E46CC9BD1E.
        /// </summary>
        internal static string MainCourseImageId {
            get {
                return ResourceManager.GetString("MainCourseImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A9DF6800D94C4149B4AD47E46CC9BD1E.
        /// </summary>
        internal static string MainCourseImageId1 {
            get {
                return ResourceManager.GetString("MainCourseImageId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Nowe hasło&apos; nie może być puste..
        /// </summary>
        internal static string NewPasswordEmptyValidationMessage {
            get {
                return ResourceManager.GetString("NewPasswordEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole &apos;Nowe hasło&apos; nie może być puste..
        /// </summary>
        internal static string NewPasswordEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("NewPasswordEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi składać się z minimum {0} znaków..
        /// </summary>
        internal static string PasswordLengthValidationMessage {
            get {
                return ResourceManager.GetString("PasswordLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi składać się z minimum {0} znaków..
        /// </summary>
        internal static string PasswordLengthValidationMessage1 {
            get {
                return ResourceManager.GetString("PasswordLengthValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena nie może być pusta..
        /// </summary>
        internal static string RateEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RateEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena nie może być pusta..
        /// </summary>
        internal static string RateEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("RateEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena musi mieścić się w skali 0-10 (liczba całkowita).
        /// </summary>
        internal static string RateValidationMessage {
            get {
                return ResourceManager.GetString("RateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena musi mieścić się w skali 0-10 (liczba całkowita).
        /// </summary>
        internal static string RateValidationMessage1 {
            get {
                return ResourceManager.GetString("RateValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole notatka nie może być puste..
        /// </summary>
        internal static string RecipeNoteEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole notatka nie może być puste..
        /// </summary>
        internal static string RecipeNoteEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("RecipeNoteEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka nie może być dłuższ niż 200 znaków..
        /// </summary>
        internal static string RecipeNoteLengthValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka nie może być dłuższ niż 200 znaków..
        /// </summary>
        internal static string RecipeNoteLengthValidationMessage1 {
            get {
                return ResourceManager.GetString("RecipeNoteLengthValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepis o podanym RecipeId nie istnieje..
        /// </summary>
        internal static string RecipeNoteRecipeExistsValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepis o podanym RecipeId nie istnieje..
        /// </summary>
        internal static string RecipeNoteRecipeExistsValidationMessage1 {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeExistsValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole RecipeId nie może być puste..
        /// </summary>
        internal static string RecipeNoteRecipeIdEmptyValidationMessage {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeIdEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole RecipeId nie może być puste..
        /// </summary>
        internal static string RecipeNoteRecipeIdEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("RecipeNoteRecipeIdEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string TagsDelimiter {
            get {
                return ResourceManager.GetString("TagsDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string TagsDelimiter1 {
            get {
                return ResourceManager.GetString("TagsDelimiter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki nie może być pusta..
        /// </summary>
        internal static string UnitEmptyValidationMessage {
            get {
                return ResourceManager.GetString("UnitEmptyValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki nie może być pusta..
        /// </summary>
        internal static string UnitEmptyValidationMessage1 {
            get {
                return ResourceManager.GetString("UnitEmptyValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o takiej nazwie już istnieje..
        /// </summary>
        internal static string UnitExistsValidationMessage {
            get {
                return ResourceManager.GetString("UnitExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka o takiej nazwie już istnieje..
        /// </summary>
        internal static string UnitExistsValidationMessage1 {
            get {
                return ResourceManager.GetString("UnitExistsValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki musi mieścić się w granicach 1-50 znaków..
        /// </summary>
        internal static string UnitValidationMessage {
            get {
                return ResourceManager.GetString("UnitValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jednostki musi mieścić się w granicach 1-50 znaków..
        /// </summary>
        internal static string UnitValidationMessage1 {
            get {
                return ResourceManager.GetString("UnitValidationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o podanej nazwie już istnieje..
        /// </summary>
        internal static string UsernameExistsValidationMessage {
            get {
                return ResourceManager.GetString("UsernameExistsValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o podanej nazwie już istnieje..
        /// </summary>
        internal static string UsernameExistsValidationMessage1 {
            get {
                return ResourceManager.GetString("UsernameExistsValidationMessage1", resourceCulture);
            }
        }
    }
}
